name: weather_station_client
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  flutter_native_splash: ^2.2.18

  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1

  flutter_bloc: ^8.1.1

  get_it: ^7.2.0
  injectable: ^2.1.0

  auto_route: ^5.0.4
  
  freezed_annotation: ^2.2.0

  json_annotation: ^4.8.0

  flutter_svg: ^2.0.7

  network_logger: ^1.0.3

  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3

  flutter_lints: ^2.0.1

  flutter_launcher_icons: "^0.12.0"

  injectable_generator: ^2.1.3

  auto_route_generator: ^5.0.3

  flutter_gen_runner: ^5.3.2

  freezed: ^2.3.2

  json_serializable: ^6.6.0

flutter_gen:
  integrations:
    flutter_svg: true

flutter:

  generate: true

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/lato_light.ttf
          style: normal
          weight: 300
        - asset: fonts/lato_light_italic.ttf
          style: italic
          weight: 300
        - asset: fonts/lato_regular.ttf
          style: normal
          weight: 400
        - asset: fonts/lato_italic.ttf
          style: italic
          weight: 400
        - asset: fonts/lato_medium.ttf
          style: normal
          weight: 500
        - asset: fonts/lato_medium_italic.ttf
          style: italic
          weight: 500
        - asset: fonts/lato_semibold.ttf
          style: normal
          weight: 600
        - asset: fonts/lato_semibold_italic.ttf
          style: italic
          weight: 600
        - asset: fonts/lato_bold.ttf
          style: normal
          weight: 700
        - asset: fonts/lato_bold_italic.ttf
          style: italic
          weight: 700
        - asset: fonts/lato_black.ttf
          style: normal
          weight: 900
        - asset: fonts/lato_black_italic.ttf
          style: italic
          weight: 900

flutter_icons:
  image_path: "assets/app_icon.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash_icon.png