name: weather_station
description: Client application for weather station

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  cupertino_icons: ^0.1.3

  # Networking
  http: ^0.12.2
  dio: ^3.0.10
  data_connection_checker: ^0.3.4

  # State management
  flutter_bloc: ^6.0.1

  # Dependency Injection
  get_it: ^4.0.4
  injectable: ^1.0.4

  # Navigation
  auto_route: ^0.6.7

  # Logging
  logger: ^0.9.2

  # Data classes & json serialization
  kt_dart: ^0.7.0+1
  freezed_annotation: ^0.11.0+1
  json_serializable: ^3.4.0

  flushbar: ^1.10.4

  flutter_svg: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Testing
  mockito: ^4.1.1

  # Generators
  build_runner: ^1.10.1
  injectable_generator: ^1.0.4
  auto_route_generator: ^0.6.8

  # Data classes
  freezed: ^0.11.5

flutter:
  uses-material-design: true

  assets:
    - lang/
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Light.ttf
          style: normal
          weight: 300
        - asset: fonts/Lato-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Lato-Regular.ttf
          style: normal
          weight: 400
        - asset: fonts/Lato-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/Lato-Medium.ttf
          style: normal
          weight: 500
        - asset: fonts/Lato-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/Lato-Semibold.ttf
          style: normal
          weight: 600
        - asset: fonts/Lato-SemiboldItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/Lato-Bold.ttf
          style: normal
          weight: 700
        - asset: fonts/Lato-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Lato-Black.ttf
          style: normal
          weight: 900
        - asset: fonts/Lato-BlackItalic.ttf
          style: italic
          weight: 900