name: weather_station
description: Client application for weather station

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0

  # Networking
  http: ^0.12.2
  dio: ^3.0.10
  data_connection_checker: ^0.3.4

  # State management
  flutter_bloc: ^6.1.0

  # Dependency Injection
  get_it: ^5.0.1
  injectable: ^1.0.5

  # Navigation
  auto_route: ^0.6.9

  # Logging
  logger: ^0.9.4

  # Data classes & json serialization
  kt_dart: ^0.8.0
  freezed_annotation: ^0.12.0
  json_serializable: ^3.5.0

  # Multi language support
  auto_localized: ^0.7.0

  # Firebase
  firebase_messaging: ^7.0.3

  # Storage
  shared_preferences: ^0.5.12+4

  flushbar: ^1.10.4

  flutter_svg: ^0.18.0

  permission_handler: ^5.0.1+1

  flutter_ble_lib: ^2.3.0

  flutter_html: ^1.0.2

  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lint
  lint: ^1.3.0

  # Testing
  mockito: ^4.1.1
  bloc_test: ^7.1.0

  # Generators
  build_runner: ^1.10.4
  injectable_generator: ^1.0.6
  auto_route_generator: ^0.6.10
  flutter_gen: ^1.2.1
  auto_localized_generator: ^0.7.1

  # Data classes
  freezed: ^0.12.2

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - lang/
    - assets/
    - assets/icons/
    - assets/images/
    - assets/json/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Light.ttf
          style: normal
          weight: 300
        - asset: fonts/Lato-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Lato-Regular.ttf
          style: normal
          weight: 400
        - asset: fonts/Lato-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/Lato-Medium.ttf
          style: normal
          weight: 500
        - asset: fonts/Lato-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/Lato-Semibold.ttf
          style: normal
          weight: 600
        - asset: fonts/Lato-SemiboldItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/Lato-Bold.ttf
          style: normal
          weight: 700
        - asset: fonts/Lato-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Lato-Black.ttf
          style: normal
          weight: 900
        - asset: fonts/Lato-BlackItalic.ttf
          style: italic
          weight: 900